baseURL = "https://golangestonia.github.io"
languageCode = "en-us"
title = "Golang Estonia"
theme = "golangestonia"

[menu]
	[[menu.main]]
		name = "Events"
		url = "/events/"
		weight = 1
	[[menu.main]]
		name = "Community"
		url = "/community/"
		weight = 2